[tools]
air = "latest"
bat = "latest"
docker-compose = "latest"
fzf = "latest"
go = "latest"
gofumpt = "latest"
java = "latest"
lua = "latest"
maven = "latest"
neovim = "latest"
node = "latest"
pipx = "latest"
python = "latest"
rust = "latest"
rust-analyzer = "latest"
tmux = "latest"
yazi = "latest"
zig = "latest"
zls = "latest"
