if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  typeset -gr _SHELL_UI_RESET=$'\033[0m'
  typeset -gr _SHELL_UI_BOLD=$'\033[1m'
  typeset -gr _SHELL_UI_DIM=$'\033[2m'
  typeset -gr _SHELL_UI_BLUE=$'\033[38;5;111m'
  typeset -gr _SHELL_UI_GREEN=$'\033[38;5;114m'
  typeset -gr _SHELL_UI_YELLOW=$'\033[38;5;221m'
  typeset -gr _SHELL_UI_RED=$'\033[38;5;203m'
  typeset -gr _SHELL_UI_CYAN=$'\033[38;5;117m'
else
  typeset -gr _SHELL_UI_RESET=''
  typeset -gr _SHELL_UI_BOLD=''
  typeset -gr _SHELL_UI_DIM=''
  typeset -gr _SHELL_UI_BLUE=''
  typeset -gr _SHELL_UI_GREEN=''
  typeset -gr _SHELL_UI_YELLOW=''
  typeset -gr _SHELL_UI_RED=''
  typeset -gr _SHELL_UI_CYAN=''
fi

typeset -gr _SHELL_ICON_OK='✔'
typeset -gr _SHELL_ICON_ERR='✖'
typeset -gr _SHELL_ICON_INFO='◆'
typeset -gr _SHELL_ICON_WARN='▲'
typeset -gr _SHELL_ICON_PKG='📦'
typeset -gr _SHELL_ICON_AUR='🧩'
typeset -gr _SHELL_ICON_DOCKER='🐳'
typeset -gr _SHELL_ICON_DB='🛢'
typeset -gr _SHELL_ICON_NET='🌐'
typeset -gr _SHELL_ICON_NOTE='✉'
typeset -gr _SHELL_ICON_BUILD='⚒'
