# Shared UI theme: ANSI color + icon helpers for shell functions.
# Portable across bash and zsh (avoid zsh-only `typeset -gr`).
# Source from bash and zsh rc files.

if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  _SHELL_UI_RESET=$'\033[0m'
  _SHELL_UI_BOLD=$'\033[1m'
  _SHELL_UI_DIM=$'\033[2m'
  _SHELL_UI_BLUE=$'\033[38;5;111m'
  _SHELL_UI_GREEN=$'\033[38;5;114m'
  _SHELL_UI_YELLOW=$'\033[38;5;221m'
  _SHELL_UI_RED=$'\033[38;5;203m'
  _SHELL_UI_CYAN=$'\033[38;5;117m'
else
  _SHELL_UI_RESET=
  _SHELL_UI_BOLD=
  _SHELL_UI_DIM=
  _SHELL_UI_BLUE=
  _SHELL_UI_GREEN=
  _SHELL_UI_YELLOW=
  _SHELL_UI_RED=
  _SHELL_UI_CYAN=
fi

_SHELL_ICON_OK='✔'
_SHELL_ICON_ERR='✖'
_SHELL_ICON_INFO='◆'
_SHELL_ICON_WARN='▲'
_SHELL_ICON_PKG='📦'
_SHELL_ICON_AUR='🧩'
_SHELL_ICON_DOCKER='🐳'
_SHELL_ICON_DB='🛢'
_SHELL_ICON_NET='🌐'
_SHELL_ICON_NOTE='✉'
_SHELL_ICON_BUILD='⚒'

export _SHELL_UI_RESET _SHELL_UI_BOLD _SHELL_UI_DIM _SHELL_UI_BLUE \
  _SHELL_UI_GREEN _SHELL_UI_YELLOW _SHELL_UI_RED _SHELL_UI_CYAN \
  _SHELL_ICON_OK _SHELL_ICON_ERR _SHELL_ICON_INFO _SHELL_ICON_WARN \
  _SHELL_ICON_PKG _SHELL_ICON_AUR _SHELL_ICON_DOCKER _SHELL_ICON_DB \
  _SHELL_ICON_NET _SHELL_ICON_NOTE _SHELL_ICON_BUILD
